# Application configuration

# Server configuration
server:
  port: 8080
  hostname: localhost

# Database configuration
database:
  url: jdbc:mysql://localhost:3306/yourdb
  username: youruser
  password: yourpassword

# Azure Key Vault configuration
azure_keyvault:
  vault_url: https://your-keyvault-name.vault.azure.net
  client_id: your-client-id
  client_secret: your-client-secret
  tenant_id: your-tenant-id
  secret_name: your-secret-name
